name: SwiftUIWebViewExample

options:
  developmentLanguage: en
  deploymentTarget:
    iOS: 15.0

packages:
  SwiftUIWebView:
    path: ../

targets:
  SwiftUIWebViewExample:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: Info.plist
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.dev.SwiftUIWebViewExample
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
    sources:
      - SwiftUIWebViewExample
    dependencies:
      - package: SwiftUIWebView

